# Generated by Django 3.2.12 on 2024-02-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='address',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='record',
            name='phoneno',
            field=models.IntegerField(max_length=12),
        ),
    ]
