# Generated by Django 3.2.12 on 2024-02-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20240223_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='phoneno',
            field=models.IntegerField(),
        ),
    ]
