# Generated by Django 3.2.12 on 2024-02-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_record_phoneno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='record',
            name='disc',
            field=models.IntegerField(default=0),
        ),
    ]
