# Generated by Django 3.2.12 on 2024-02-23 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20240223_0536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='phoneno',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='record',
            name='disc',
        ),
    ]
